name: crispr
channels:
  - anaconda
  - esrf-bcu
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.11
  - appdirs=1.4.4
  - argtable2=2.13
  - aria2=1.37.0
  - attr=2.5.1
  - aws-c-auth=0.7.20
  - aws-c-cal=0.6.12
  - aws-c-common=0.9.17
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.8
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.329
  - beautifulsoup4=4.12.3
  - biopython=1.83
  - blas=1.1
  - blast=2.15.0
  - blast-legacy=2.2.26
  - bokeh=3.4.1
  - bottleneck=1.3.8
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.16.0
  - click=8.1.7
  - cloudpickle=3.0.0
  - clustalo=1.2.4
  - clustalw=2.1
  - contourpy=1.2.1
  - cryptography=42.0.7
  - curl=8.7.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.5.1
  - dask-core=2024.5.1
  - dask-expr=1.1.1
  - dbus=1.13.6
  - dendropy=5.0.1
  - diff-match-patch=20230430
  - distributed=2024.5.1
  - entrez-direct=21.6
  - ete3=3.1.3
  - expat=2.6.2
  - fasttree=2.1.11
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.52.4
  - forgi=2.0.3
  - freetype=2.12.1
  - fsspec=2024.5.0
  - future=1.0.0
  - gawk=5.3.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - git=2.45.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.7.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - gsl=2.7
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - harfbuzz=8.5.0
  - hmmer=3.4
  - icu=73.2
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - jinja2=3.1.4
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - levenshtein=0.25.1
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.5
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.7.1
  - libdb=6.2.32
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.10.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=3.0.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgpg-error=1.49
  - libgrpc=1.62.2
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm18=18.1.5
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnuma=2.0.12
  - libogg=1.3.4
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.6
  - libxslt=1.1.39
  - libzlib=1.2.13
  - locket=1.0.0
  - logging_exceptions=0.1.8
  - lxml=5.2.2
  - lz4=4.3.3
  - lz4-c=1.9.4
  - mafft=7.526
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mmseqs2=15.6f452
  - mpfr=4.2.1
  - mpg123=1.32.6
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - muscle=5.1
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncbi-vdb=3.1.0
  - ncurses=6.4.20240210
  - networkx=3.1
  - nomkl=1.0
  - nspr=4.35
  - nss=3.98
  - numexpr=2.9.0
  - numpy=1.26.4
  - openblas=0.3.27
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.0
  - packaging=24.0
  - paml=4.10.7
  - pandas=2.1.1
  - partd=1.4.2
  - pathlib=1.0.1
  - pcre=8.45
  - pcre2=10.43
  - perl=5.32.1
  - perl-algorithm-diff=1.201
  - perl-archive-tar=2.40
  - perl-b-hooks-endofscope=0.26
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-featureio=1.6.905
  - perl-bio-samtools=1.43
  - perl-bio-searchio-hmmer=1.7.3
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bioperl-core=1.7.8
  - perl-bioperl-run=1.007003
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-carp=1.50
  - perl-class-data-inheritable=0.09
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-constant=1.33
  - perl-cpan-meta-check=0.014
  - perl-data-dumper=2.183
  - perl-data-optlist=0.113
  - perl-db_file=1.858
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.007
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.04
  - perl-digest-md5=2.58
  - perl-dist-checkconflicts=0.11
  - perl-encode=3.21
  - perl-encode-locale=1.05
  - perl-eval-closure=0.14
  - perl-exception-class=1.45
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-file-listing=6.16
  - perl-file-pushd=1.016
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-spec=3.48_01
  - perl-getopt-long=2.54
  - perl-html-parser=3.81
  - perl-html-tagset=3.20
  - perl-http-cookies=6.10
  - perl-http-daemon=6.16
  - perl-http-date=6.06
  - perl-http-message=6.36
  - perl-http-negotiate=6.01
  - perl-inc-latest=0.500
  - perl-io-compress=2.201
  - perl-io-html=1.004
  - perl-io-socket-ssl=2.075
  - perl-io-string=1.08
  - perl-io-tty=1.16
  - perl-io-zlib=1.14
  - perl-ipc-run=20200505.0
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-libwww-perl=6.67
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-lwp-mediatypes=6.04
  - perl-mime-base64=3.16
  - perl-module-build=0.4234
  - perl-module-implementation=0.09
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moose=2.2207
  - perl-mro-compat=0.15
  - perl-namespace-clean=0.27
  - perl-net-http=6.22
  - perl-net-ssleay=1.92
  - perl-ntlm=1.09
  - perl-package-deprecationmanager=0.18
  - perl-package-stash=0.40
  - perl-package-stash-xs=0.30
  - perl-params-util=1.102
  - perl-parent=0.241
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.63
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-sub-exporter=0.989
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-sub-install=0.928
  - perl-sub-name=0.26
  - perl-sub-uplevel=0.2800
  - perl-test-cleannamespaces=0.24
  - perl-test-deep=1.130
  - perl-test-differences=0.71
  - perl-test-exception=0.43
  - perl-test-fatal=0.016
  - perl-test-leaktrace=0.17
  - perl-test-most=0.38
  - perl-test-warn=0.37
  - perl-test-warnings=0.031
  - perl-text-diff=1.45
  - perl-time-local=1.35
  - perl-timedate=2.33
  - perl-tree-dag_node=1.32
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-uri=5.17
  - perl-url-encode=0.03
  - perl-variable-magic=0.63
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-xpathengine=0.14
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - ply=3.11
  - poa=2.0
  - prodigal=2.6.3
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pyftpdlib=1.5.9
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-levenshtein=0.25.1
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - rapidfuzz=3.8.1
  - re2=2023.09.01
  - readline=8.2
  - s2n=1.4.13
  - scandir=1.10.0
  - scipy=1.11.3
  - seqkit=2.8.2
  - setuptools=69.2.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - tblib=3.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - tzdata=2024a
  - upsetplot=0.9.0
  - urllib3=2.2.1
  - wget=1.21.4
  - wheel=0.43.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.41
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - attrs==24.3.0
      - blinker==1.4
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - chardet==5.2.0
      - cssselect2==0.7.0
      - defusedxml==0.7.1
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - hyperframe==6.0.1
      - idna==3.10
      - kaitaistruct==0.10
      - outcome==1.3.0.post0
      - pyasn1==0.6.1
      - pypdf2==3.0.1
      - reportlab==4.2.5
      - selenium==4.27.1
      - selenium-wire==5.1.0
      - sniffio==1.3.1
      - svglib==1.5.1
      - tinycss2==1.4.0
      - trio==0.27.0
      - trio-websocket==0.11.1
      - typing-extensions==4.12.2
      - viennarna==2.6.4
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wsproto==1.2.0
      - zstandard==0.23.0